[package]
name = "tester"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
algo_lib = { path = "../algo_lib" }
pretty_assertions = "1.4"

[features]
test = []
