pub mod arr2d;
pub mod arr3d;
pub mod arr4d;
pub mod arr5d;
pub mod bit_set;
pub mod default_map;
pub mod dsu;
pub mod dsu2d;
pub mod fenwick;
pub mod id;
pub mod indexed_heap;
pub mod iter_ext;
pub mod legacy_fill;
pub mod min_max;
pub mod permutation;
pub mod persistent_fenwick;
pub mod segment_tree;
#[cfg(test)]
mod test;
pub mod treap;
pub mod treap_map;
pub mod vec_ext;
